In [1]:
import numpy as np


In [3]:
M=np.array([[1,2],[3,4]]) #np 2-darray

In [4]:
l=[[1,2],[3,4]]

In [5]:
l[0]

[1, 2]

In [6]:
l[0][0]

1

In [8]:
M[0][0]

1

In [9]:
M[0,0]  # more easy to use

1

In [10]:
M2=np.matrix([
    [1,2],[3,4]
])

In [11]:
M2

matrix([[1, 2],
        [3, 4]])

In [13]:
m1=np.array(M2)   #it is highly recommended to convert any matrix to numpy array
m1

array([[1, 2],
       [3, 4]])

In [15]:
m1.T #transpose of matrix

array([[1, 3],
       [2, 4]])

In [16]:
##Generating matrix to work with

In [18]:
Z=np.zeros(10)# this will create vector of 10 elements of value equal to 0
Z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [19]:
z=np.zeros((10,5))
z

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [20]:
o=np.ones([5,10])

In [21]:
o


array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [22]:
m=np.random.random((10,10))  #random numbers(smaller than 1  and greater than 0)


In [23]:
m

array([[ 0.87912176,  0.58334965,  0.49014208,  0.96038733,  0.3979412 ,
         0.74233476,  0.39392804,  0.20223233,  0.59395836,  0.89831129],
       [ 0.70975273,  0.47492709,  0.89157655,  0.01907463,  0.63940134,
         0.60346114,  0.09639655,  0.49429459,  0.98224315,  0.04907119],
       [ 0.34826225,  0.15006079,  0.49635   ,  0.48744415,  0.46657491,
         0.93841338,  0.68486575,  0.44988894,  0.22693767,  0.06376793],
       [ 0.70804374,  0.2742412 ,  0.50609293,  0.56328026,  0.59496026,
         0.36650378,  0.09038412,  0.64071792,  0.85493315,  0.15436958],
       [ 0.31111516,  0.33139808,  0.03440808,  0.90532438,  0.50519202,
         0.59211046,  0.90874467,  0.26842063,  0.46612759,  0.41572805],
       [ 0.34919225,  0.54773402,  0.55128733,  0.14443451,  0.97024284,
         0.75827777,  0.79315915,  0.51557686,  0.97039791,  0.34059022],
       [ 0.90440605,  0.66748252,  0.12033327,  0.68228873,  0.42403456,
         0.64461695,  0.83245316,  0.8010071 

In [24]:
m.mean() #mean

0.55981462768194423

In [25]:
m.var() #variance

0.073801231282106472

In [26]:
G=np.random.randn(10,10)

In [27]:
G

array([[-0.29260863,  1.0276008 ,  1.81002503, -2.14992491,  1.17762569,
         1.05207141,  0.8380857 ,  0.79743597, -0.5596817 , -0.97975104],
       [-0.86003076, -0.0756407 , -0.49734653, -0.19087244,  0.59932444,
         0.62912823,  0.70238371, -1.6246037 , -0.39306614,  1.04036345],
       [ 0.89842589,  1.45288252, -1.2291735 , -0.40763314,  0.32216248,
         1.95669427,  0.14675257, -0.35643429,  1.9338971 , -0.98408893],
       [ 0.45197037, -0.65402083, -0.86320269,  1.56754138, -1.23846138,
         0.8687288 , -0.03193023,  0.40639984,  0.69101295, -0.2194854 ],
       [ 1.07433823,  0.14955101,  1.49286704, -0.18117451, -1.40417553,
        -1.29994971, -1.69485752,  0.03873181,  0.41029368,  1.08678974],
       [ 0.43807489,  1.05616958,  1.6055141 , -0.93782762,  0.09772973,
         0.79692812,  0.73092187, -0.23143717, -0.31781387,  1.19314565],
       [-0.3051291 ,  0.06198947,  0.23240057, -1.09502383, -0.97743045,
         0.795534  ,  1.1415037 ,  0.25496081

In [28]:
#############inverse

In [30]:
A=np.array([[1,2],[3,4]])
Ainv=np.linalg.inv(A)
Ainv


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [31]:
A.dot(Ainv)

array([[  1.00000000e+00,   1.11022302e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [32]:
Ainv.dot(A)

array([[  1.00000000e+00,   4.44089210e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [33]:
np.linalg.det(A)

-2.0000000000000004

In [34]:
np.diag(A)##if you pass 2d array u will get 1 d array,if u pass 1 d array u will get 2d array

array([1, 4])

In [35]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [36]:
A=np.array([1,2])
B=np.array([3,4])
np.outer(A,B)


array([[3, 4],
       [6, 8]])

In [38]:
np.inner(A,B)#dot product

11

In [39]:
A.dot(B)

11

In [43]:
###sum of dia9g
np.diag(A).sum()


3

In [44]:
x=np.random.randn(100,3)

In [45]:
x

array([[  1.75847148e+00,  -1.82607495e+00,   1.34322205e+00],
       [ -8.72546070e-01,  -7.02432368e-01,  -4.11667394e-01],
       [ -1.27563989e+00,   2.99246051e-01,   3.52997914e-01],
       [ -1.70700902e-01,  -6.68762574e-01,   1.64570560e+00],
       [  5.26740737e-01,   1.66566549e-01,   1.56753889e+00],
       [ -1.08152978e+00,   1.56738640e-01,  -1.24704812e+00],
       [ -4.91963314e-01,  -4.03025561e-01,   1.09954562e+00],
       [  3.42138471e-01,   4.95256849e-01,   6.51699239e-01],
       [ -5.94820597e-01,   7.17962424e-01,   6.23963363e-01],
       [  1.02549592e+00,   1.41901803e-01,  -2.54487743e-01],
       [  5.15019978e-01,   2.25558746e+00,   1.71257883e-01],
       [  1.67204982e+00,  -1.01095469e+00,  -1.91589332e-01],
       [  8.06935737e-01,   6.82044840e-01,   2.64233180e+00],
       [  6.02886045e-02,  -1.52256829e+00,  -1.78419011e-01],
       [ -1.06964365e+00,  -2.94523478e-01,   5.35491885e-01],
       [  5.92972632e-01,  -2.68674656e-01,   8.1471834

In [47]:
cov=np.cov(x)  #covariance

In [49]:
cov.shape

(100, 100)

In [50]:
cov=np.cov(x.T)

In [51]:
cov


array([[ 1.00291174, -0.00332648, -0.01726217],
       [-0.00332648,  1.04986297, -0.00950666],
       [-0.01726217, -0.00950666,  0.95221969]])

In [53]:
np.linalg.eigh(cov) ##eighen values and eigen vectors

(array([ 0.94592509,  1.00822839,  1.05084092]),
 array([[ 0.29370665,  0.9551852 ,  0.03684626],
        [ 0.09638516,  0.00875675, -0.99530559],
        [ 0.95102382, -0.2958793 ,  0.08949376]]))