In [1]:
#while using numpy we will cosider it to be list to be vector



import numpy as  np
l=[1,2,3]#arraylist

In [2]:
A=np.array([1,2,3])#numpyarray

In [7]:
for e in l:print(e)

1
2
3


In [8]:
l.append(4)#addition, append in numpy add element to list

In [9]:
l


[1, 2, 3, 4]

In [10]:
#         + do matrix addition rather than appendind list

In [11]:
A+A # addition of two vectors

array([2, 4, 6])

In [12]:
2*A #multiplication of vector by scalar


array([2, 4, 6])

In [13]:
2*l #multiplication in list double the element

[1, 2, 3, 4, 1, 2, 3, 4]

In [14]:
l**2 #doesn't work with list

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [15]:
 A**2 # square of each element if vector, in list we want this list we have to use loop which is not good practice

array([1, 4, 9])

In [16]:
np.sqrt(A)

array([ 1.        ,  1.41421356,  1.73205081])

In [17]:
np.log(A)

array([ 0.        ,  0.69314718,  1.09861229])

In [18]:
np.exp(A)

array([  2.71828183,   7.3890561 ,  20.08553692])

In [20]:
#########dot product


In [21]:
a=np.array([1,2])

In [22]:
b=np.array([2,1])
a*b

array([2, 2])

In [23]:
np.sum(a*b)

4

In [24]:
np.dot(a,b)

4

In [25]:
cosine=a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))

In [26]:
cosine

0.79999999999999982

In [27]:
theta= np.arccos(cosine)

In [28]:
theta#rad


0.6435011087932847