In [1]:
import numpy as np


In [2]:
a=np.array([[1,2],[3,4]])
b=np.array([1,2])


In [3]:
x=np.linalg.inv(a).dot(b)

In [4]:
x

array([  2.22044605e-16,   5.00000000e-01])

In [5]:
x=np.linalg.solve(a,b)

In [6]:
x

array([ 0. ,  0.5])

In [7]:
#the admission fee at a small fair is $1.50 for children and $4.00 for adult.On certain day,2200 people enter the
#fair and $5050 is collected.How many children and how many adults attended?

In [9]:
# let x1=no.of children
# let x2=no.ofadults


#  x1+x2=2200
#  1.5x1+ 4x2=5050

In [13]:
a=np.array([[1,1],[1.5,4]])
b=np.array([2200,5050])

In [14]:
np.linalg.solve(a,b)

array([ 1500.,   700.])